INSERT INTO `helioapibd`.`nonlocalproducts` (`nombreProducto`, `descripcion`, `stock`, `marca`, `urlreference`, `precio`, `empresa`) VALUES ('Pulidor Kenda Unicus', 'Sistema de pulido diamantado en 1 solo paso para restauraciones con composite y ceramica. Un solo pulidor consigue un acabado y pulido perfectos de todas las restauraciones de composite y de ceramica con una buena relacion coste-eficiencia.', '360', 'Kenda', 'http://www.kenda-dental.com/DesktopModules/ToSic_KendaProductCatalog/Thumbnail.aspx?Image=%2fKenda%2fProductImages%2fNobilis%2f1.jpg&Width=430&Height=280', '53.50', 'Kenda dental polishers');
INSERT INTO `helioapibd`.`nonlocalproducts` (`nombreProducto`, `descripcion`, `stock`, `marca`, `urlreference`, `precio`, `empresa`) VALUES ('Caja de esterilizacion Kenda Practicus', 'La caja de esterilizacion Kenda Practicus esta concebida para 6 pulidores contra-angulo y 12 instrumentos FG diamantados. Para organizar y preparar su trabajo.', '400', 'Kenda', 'http://www.kenda-dental.com/DesktopModules/ToSic_KendaProductCatalog/Thumbnail.aspx?Image=%2fKenda%2fProductImages%2fPracticus%2f1.jpg&Width=430&Height=280', '169.90', 'Kenda dental polishers');
INSERT INTO `helioapibd`.`nonlocalproducts` (`nombreProducto`, `descripcion`, `stock`, `marca`, `urlreference`, `precio`, `empresa`) VALUES ('Cemento de Obturacion Provisional (Jeringas 3x3gr)', 'Cemento de obturacion provisional para restauraciones temporales: Fotopolimerizable.', '410', 'Medicaline', 'https://www.dentaltix.com/es/sites/default/files/styles/large/public/obturacion-provisional.jpg?itok=Zx6Y0PM0', '45.07', 'Dentaltix');
INSERT INTO `helioapibd`.`nonlocalproducts` (`nombreProducto`, `descripcion`, `stock`, `marca`, `urlreference`, `precio`, `empresa`) VALUES ('Lampara de Fotocurado Inalambrica (Kit)', 'Lampara inalambrica LED para fotocurado. Cuenta con tres modos de potencia: Estandar, Alta Potencia y Potencia Extra. Diseño ligero, delgado y ergonomico para facilitar el acceso a todas las zonas de la boca.', '312', 'Ultradent', 'https://www.dentaltix.com/es/sites/default/files/styles/large/public/5944_valo-cordless-kit-graphite-open_equipment_0.jpg?itok=ak6cWack', '966.79', 'Dentaltix');
INSERT INTO `helioapibd`.`nonlocalproducts` (`nombreProducto`, `descripcion`, `stock`, `marca`, `urlreference`, `precio`, `empresa`) VALUES ('Dentrifico SENSODYNE', 'Sensodyne ayuda a aliviar la sensibilidad dental y se esfuerza para crear un futuro sin sensibilidad dental para todos.', '330', 'Sensodyne', 'https://i-cf5.gskstatic.com/content/dam/cf-consumer-healthcare/sensodyne-v2/en_US/Product-pages/products/desktop/Product-Repair-Protect.png?auto=format', '7.17', 'Sensodyne');
INSERT INTO `helioapibd`.`nonlocalproducts` (`nombreProducto`, `descripcion`, `stock`, `marca`, `urlreference`, `precio`, `empresa`) VALUES ('Dentifrico Protect sensitive Dentalyss', 'Dentifrico Protect Encias Gengive Dentalyss 75 Ml.', '400', 'Dentalyss', 'https://d2ohdpvxj0yo9f.cloudfront.net/products/de/dentfrico-protect-gencives-dentalyss-75ml-de-carrefour-es-1621989234_m.jpg', '0.96', 'Lola market');
INSERT INTO `helioapibd`.`nonlocalproducts` (`nombreProducto`, `descripcion`, `stock`, `marca`, `urlreference`, `precio`, `empresa`) VALUES ('Hilo dental Plackers ', 'Ayuda a llegar facilmente a los dientes con el diseño de angulo recto.', '470', 'Plackers', 'https://images-na.ssl-images-amazon.com/images/I/4109DMW%2B-rL.jpg', '23.95', 'Ebay');
INSERT INTO `helioapibd`.`nonlocalproducts` (`nombreProducto`, `descripcion`, `stock`, `marca`, `urlreference`, `precio`, `empresa`) VALUES ('Enjuague Bucal KIN Gingival Complex', 'Enjuague bucal en frasco de 250ml Clorhexidina 0.12% + Alpantha. Refuerza y tonifica las encias delicadas.', '310', 'KIN', 'https://dentalkin.com/wp-content/uploads/2018/06/Producto_KIN_GINGIVAL_COMPLEX_ENJUAGUE_KINGINGIVALCOMPLEX_ENJUAGUE-768x768.png', '12.56', 'KIN');
INSERT INTO `helioapibd`.`nonlocalproducts` (`nombreProducto`, `descripcion`, `stock`, `marca`, `urlreference`, `precio`, `empresa`) VALUES ('Enjuague Bucal ODDENT', 'ODDENT acido hialuronico es un enjuague bucal de uso diario adecuado para el control de la placa bacteriana y la prevencion de la caries. Contiene lactato de zinc y cloruro de cetilpiridinio, dos agentes que actuan contra la placa bacteriana. Esta accion se ve reforzada por el fluoruro potasico, que ayuda tambien a prevenir la caries.', '446', 'ODDENT', 'https://menarini-ca.com/images/Fotos_Vademecum_nuevas/18Dental/02Oddent/B5-Enjuague-Composicion3D-Final.png', '11.94', 'Amazon');
